# Generated by Django 3.0.6 on 2020-05-22 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletargetmodel',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='department',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
