# Generated by Django 3.0.6 on 2020-05-22 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0002_auto_20200522_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodulemodel',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
