# Generated by Django 3.0.6 on 2020-05-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0003_departmentmodulemodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentGroupModuleTargetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True)),
                ('department_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_management.DepartmentModel')),
                ('module_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_management.ModuleTargetModel')),
            ],
        ),
        migrations.DeleteModel(
            name='DepartmentGroupModuleModel',
        ),
    ]
