# Generated by Django 3.0.6 on 2020-05-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0004_auto_20200522_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentgroupmodel',
            name='department_group',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
